### PR TITLE
1.19.3

### PR DESCRIPTION
**Pull request by djlawler**
Update to 1.19.3

### CODE REVIEW

**Comment by mattyalanestock** [comment]
Compiled & worked in-game for me, good job, thanks! 😎

**Review by mattyalanestock — APPROVED** [review]
Compiled & worked in-game for me, good job, thanks! 😎

**Comment by The-Stive-man** [comment]
compiled this today and tried it on Fabric 0.14.17-1.19.3 and the game crashes.

**Comment by Trainmaster2** [comment]
It worked fine for me. I don't know if the fact I'm using Quilt made a difference.

**Comment by The-Stive-man** [comment]
> It worked fine for me. I don't know if the fact I'm using Quilt made a difference.

If I launch client in eclipse this works great, but the jar I'm making fails even after reverting to Fabric 0.14.12 and using the 0.71.0 API... what am I missing??

**Comment by The-Stive-man** [comment]
Got it working! This is great. I was making a dumb move in the jar creation and asking eclipse to handle that

**Review by jijirae — APPROVED** [review]
Works. Thanks a ton!

**Comment by djlawler** [comment]
Hey for a similar working 1.19.4 version, try https://github.com/end-user/FlightHud

**Pull request closed without merging**
